# Generated by Django 5.0.7 on 2025-08-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficiary_address_beneficiary_address_complement_and_more'),
        ('core', '0002_beneficiary_identifier_global_unique'),
    ]

    operations = [
    ]
