# Generated by Django 5.0.7 on 2025-08-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20250809_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome da família')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('SELF', 'Titular'), ('CHILD', 'Filho(a)'), ('SPOUSE', 'Cônjuge'), ('OTHER', 'Outro')], default='SELF', max_length=16)),
                ('is_guardian', models.BooleanField(default=False, verbose_name='É responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='distribution',
            name='uniq_distribution_per_beneficiary_month_org',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='core.beneficiary'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.family'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('beneficiary',), name='uniq_beneficiary_single_family'),
        ),
    ]
