# Generated by Django 5.0.7 on 2025-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_family_familymember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='document',
            field=models.CharField(blank=True, max_length=50, verbose_name='CPF'),
        ),
    ]
