# Generated by Django 5.0.7 on 2025-08-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guardian_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiário', 'verbose_name_plural': 'Beneficiários'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Distribuição', 'verbose_name_plural': 'Distribuições'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Família', 'verbose_name_plural': 'Famílias'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Membro da família', 'verbose_name_plural': 'Membros da família'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organização', 'verbose_name_plural': 'Organizações'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Movimentação de estoque', 'verbose_name_plural': 'Movimentações de estoque'},
        ),
        migrations.CreateModel(
            name='OrganizationBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.beneficiary')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='core.organization')),
            ],
            options={
                'verbose_name': 'Vínculo organização/beneficiário',
                'verbose_name_plural': 'Vínculos organização/beneficiário',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationbeneficiary',
            constraint=models.UniqueConstraint(fields=('organization', 'beneficiary'), name='uniq_organization_beneficiary_membership'),
        ),
    ]
