# Generated by Django 5.0.7 on 2025-08-09 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_attendance_options_alter_beneficiary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distribution',
            name='uniq_distribution_per_beneficiary_month_network',
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.UniqueConstraint(fields=('beneficiary', 'product', 'period_month'), name='uniq_distribution_per_beneficiary_product_month_network'),
        ),
    ]
