# Generated by Django 5.0.7 on 2025-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_distribution_unique_by_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
