name: Deploy

on:
  push:
    branches:
      - dev
      - homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Selecionar ambiente por branch
        id: select_env
        shell: bash
        run: |
          ref_name="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          if [[ "$ref_name" == "main" ]]; then
            echo "env=prod" >> "$GITHUB_OUTPUT"
          elif [[ "$ref_name" == "homolog" ]]; then
            echo "env=homolog" >> "$GITHUB_OUTPUT"
          else
            echo "env=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Mostrar ambiente selecionado
        shell: bash
        run: |
          echo 'Selected environment: ${{ steps.select_env.outputs.env }}'

      - name: Debug workspace
        shell: bash
        run: |
          set -euxo pipefail
          pwd
          ls -la
          ls -la Solidariza || true
          docker --version

      - name: Build Docker image
        shell: bash
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          set -euxo pipefail
          # Usa a pasta do projeto Django como contexto para que o Dockerfile encontre requirements.txt
          docker build -f Solidariza/Dockerfile -t solidariza:${{ steps.select_env.outputs.env }} Solidariza

      - name: Save artifact
        run: |
          docker save solidariza:${{ steps.select_env.outputs.env }} | gzip > solidariza_${{ steps.select_env.outputs.env }}.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: solidariza_${{ steps.select_env.outputs.env }}
          path: solidariza_${{ steps.select_env.outputs.env }}.tar.gz


